### ISSUE TITLE
Hardcoded information, you can use them from object?

### ISSUE THREAD

**Issue by eidosam** [SarKurd/hyf-javascript2#3]
https://github.com/SarKurd/hyf-javascript2/blob/2c283d7089b7943009dae3e85e5199b1233ed86d/week1/script.js#L74-L83

Key **the_hobbit** is already known programmatically by variable `element` so they don't need to be in `switch ... case` 
The title **The hobbit** you could generate it here as you already have done in the previous step https://github.com/SarKurd/hyf-javascript2/blob/2c283d7089b7943009dae3e85e5199b1233ed86d/week1/script.js#L48

So maybe you can take them out of `switch`, replacing the hardcoded parts with the variable `element` like?

    arrayOfBookCoversKeys.forEach(element => {
        let anIMG = document.createElement("img");
        let theLi = document.getElementById(element);
        anIMG.setAttribute("alt", element.charAt(0).toUpperCase() + element.slice(1));
        anIMG.setAttribute("src", bookCovers[element]);
        theLi.appendChild(anIMG);
    });

**Comment by SarKurd** [comment]
1- That's true, i shouldn't have used hardcoded information
2- i used switch because the last step of the HW made me confusing when it said the key in Objects aren't ordered and may give unexpected result, that's why i used switch but looks like i misunderstood, thanks for clarifying
3- element.charAt(0).toUpperCase() + element.slice(1) will capitalise only the first letter but i already have done this one too so i basically used `objectOfBooksNames[element]["title"]`

here the the final code and it works.

`function addImagesToTheli(){
    let arrayOfBookCoversKeys = Object.keys(bookCovers);
    arrayOfBookCoversKeys.forEach(element => {
                let anIMG = document.createElement("img");
                let theLi = document.getElementById(element);
                anIMG.setAttribute("alt", objectOfBooksNames[element]["title"]);
                anIMG.setAttribute("src", bookCovers[element]);
                theLi.appendChild(anIMG);
    });
}`

Thanks

**Comment by eidosam** [comment]
+1

**Comment by eidosam** [comment]
Solved in 43172ec92cbe3eda833da3a616fbaad5991ac103
